name: Build

on:
  push:
  pull_request:
  release:

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate
      
    - name: Cache Composer dependencies
      uses: actions/cache@v2
      with:
        path: /tmp/composer-cache
        key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
    
    - name: Install dependencies
      uses: php-actions/composer@v6
      with:
        php_version: 8.0

    - name: Test
      if: ${{ success() }}
      run: composer test
